### ISSUE TITLE
Unable to upgrade to 1.1.6

### ISSUE THREAD

**Issue by RyanRoberts** [a-digital/cookie-consent-banner#10]
I'm having trouble upgrading to the latest version, this is the error I get when updating via Composer:

``` composer upgrade adigital/cookie-consent-banner
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package adigital/cookie-consent-banner v1.1.6 exists as adigital/cookie-consent-banner[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.3-beta.1, 1.1.4, 1.1.5, dev-master] but these are rejected by your constraint.
```

I'm a little unsure about what I should be doing here.

If I run `./craft update cookie-consent-banner` I get a PHP Fatal Error message about memory :/

**Comment by RyanRoberts** [comment]
Well I don't know what the difference is but running the update from within Craft itself was successful ¯\\_(ツ)_/¯

**Comment by mark-adigital** [comment]
Glad the problem is resolved for you now - thanks for updating/closing the issue too!
