### ISSUE TITLE
How to set Opt-In function

### ISSUE THREAD

**Issue by olsp** [a-digital/cookie-consent-banner#14]
Hi! 
I just installed the plugin and chose the "Opt-In" type, but do I set the script, that should be included now?
In the console, it says "Opt in function not defined!" but I can't find any information in the settings or documentation.

Oliver

**Comment by mark-adigital** [comment]
Hi Oliver,

The banner rendered by the plugin is [Osano's](https://www.osano.com/cookieconsent/documentation/javascript-api/) and the way I've handled the various opt in/out scenarios is based on [their documentation](https://www.osano.com/cookieconsent/documentation/disabling-cookies/).

So if the banner is an opt in type and consent has been granted, a JavaScript function called `optInCookiesConsented()` is executed by the plugin - as long as you've declared this function with the logic of what you want to happen in this case (namely enabling/setting cookies), it should work.

The other situations involve three other functions and are as follows:

- Opt out banner and consent not given, `optOutCookiesNotConsented()` is executed to disable cookies.
- Opt in banner and consent given, status changed from previous, `optInCookiesConsented()` called to enable cookies.
- Opt out banner and consent not given, status changed from previous, `optOutCookiesNotConsented()` called to disable cookies.
- Opt in banner and choice revoked `optInCookiesRevoked()` called to disable cookies.
- Opt out banner and choice revoked `optOutCookiesRevoked()` called to enable cookies.

These settings are all relatively new, and you may well be the first person to really use them! The plugin started as really quite simple, but it's moved on enough that I do need to revisit the readme file at some point, too. I also spotted when looking at this for you that a couple of the function calls detailed above were wrong, so I've corrected those and published a new release.

Hope that helps,

Mark

**Comment by mark-adigital** [comment]
Hi Oliver,

Are you still having problems or are you happy for me to close this issue now?

Mark

**Comment by olsp** [comment]
Thanks for the explanation and the great work!
