### ISSUE TITLE
Option to follow Do Not Track Option

### ISSUE THREAD

**Issue by olsp** [a-digital/cookie-consent-banner#15]
Hi Mark!

It would be great to have a setting where one could follow the Do Not Track Option of the user. So if the user has chosen this option, the cookie consent bar isn't shown and it is handled like the user has opted-out.

What do you think about it?

Thanks for this great plugin, btw!
Oliver

**Comment by mark-adigital** [comment]
Hi Oliver,

Can you try the most recent release please? Where a 'Do Not Track' header has been sent and the settings are configuring to honour this, a `optOutCookiesNotConsented()` JS function will be called wherein cookies can be disabled.

Hope that helps,

Mark

**Comment by mark-adigital** [comment]
Hi Oliver,

Are you happy for me to close this issue now?

Mark

**Comment by olsp** [comment]
Hi Mark,

thanks for getting this done so quickly (and sorry for not replying sooner :( ). It's great to have this option now. 
But I'm not sure if it's working correctly. Currently I only see the message "Opt out cookies not consented" in the console but no cookie bar. No matter if I have do-not-track enabled or not in the browser.

**Comment by mark-adigital** [comment]
No worries Oliver.

That's unusual - it seems to be working for me. Can you try clearing your cookies for the domain first, just to rule out any previously set cookies from interfering? Failing that, which browser are you using?
