### ISSUE TITLE
composer update won't install 1.2.4 or 1.2.5 - Maybe 2019/2020 year issue

### ISSUE THREAD

**Issue by rogerdawkins** [a-digital/cookie-consent-banner#16]
I've run composer update on a project today and it will only update to 1.2.3. I've checked the composer.json file and the version constraints look fine.

I did notice in my Craft install it is showing 1.2.4 and 1.2.5 but they both are showing dates of **20/01/2019** and it should be **2020**! I don't know whether the earlier dates are causing the problem or whether that is a red herring.

**Comment by tim-pixeldeluxe** [comment]
It looks like 1.2.4 and 1.2.5 are not available on packagist while they do on github. So Craft allows you to update but the version can't be installed by composer. @mark-adigital

**Comment by rogerdawkins** [comment]
@tim-pixeldeluxe OK, that makes sense. I didn't try the update through Craft but I'll give that a go.

**Comment by mark-adigital** [comment]
Thanks for bringing this to our attention - basically my colleague and I were unable to see each other's repos in Packagist when one of our Github accounts was connected despite being under the same organisation. We've ultimately figured out that this can be resolved by connecting our bosses account instead as he owns the organisation.

I've updated the Readme years too, thanks for pointing that out but don't think it was causing any major issues.

**Comment by rogerdawkins** [comment]
Perfect, all updated via composer.

**Comment by mark-adigital** [comment]
Great - thanks for confirming that!
