### ISSUE TITLE
What if user opts out?

### ISSUE THREAD

**Issue by bartrylant** [a-digital/cookie-consent-banner#17]
How should I handle users that opted out of cookies? Is there a variable that gets set which I can check to see if the user has allowed cookies or not? Or what would be the best way to handle this?

**Comment by mark-adigital** [comment]
Yes - I need to improve the documentation after a large raft of updates late last year, but I think [this answer](https://github.com/a-digital/cookie-consent-banner/issues/14#issuecomment-576256256) covers what you're asking.

**Comment by mark-adigital** [comment]
Hi - are you happy for me to close this issue now?

**Comment by bartrylant** [comment]
I've read it but I'm not really sure yet how to do it... I'm using [this plugin](https://github.com/nystudio107/craft-cookies) to set and retrieve cookies. According to the docs from the post you are referring to above, I should write my own javascript logic and set the cookies with javascript?

**Comment by mark-adigital** [comment]
Yep, so the JavaScript named in that answer are executed depending on what sort of validation type you have selected and what the user chooses. So you would need to write a function with the relevant name that then enables/disables whatever cookies you are setting as appropriate. The intention is that you would do this with JavaScript, but there's no reason why you couldn't write an AJAX call that could then use the Cookies plugin you link to. Does that help clarify things?

**Comment by mark-adigital** [comment]
Hi Bart, have you managed to achieve what you were going for with the plugin?
