### ISSUE TITLE
Internal server error upon deploy.

### ISSUE THREAD

**Issue by Geestig** [a-digital/cookie-consent-banner#18]
On the latest Craft version 3.4.4 I seem to get an internal server error whenever I deploy the site with the plugin enabled. Had a similar issue with CP-Nav so this might be Craft related though.

**Comment by mark-adigital** [comment]
Thanks - to be honest, I won't have time to look at this until next week now (which may also give an opportunity for a Craft update that may resolve the issue). Nothing in the [updating plugins for 3.4](https://craftcms.com/guides/updating-plugins-for-craft-34) article jumped out at me as needing an update, but maybe there is something I've missed.

**Comment by Geestig** [comment]
> Thanks - to be honest, I won't have time to look at this until next week now (which may also give an opportunity for a Craft update that may resolve the issue). Nothing in the [updating plugins for 3.4](https://craftcms.com/guides/updating-plugins-for-craft-34) article jumped out at me as needing an update, but maybe there is something I've missed.

np, just wanted to give a heads up. I'll use the javascript cookieconsent plugin in the meanwhile.

**Comment by mark-adigital** [comment]
Hey, are you still seeing this issue? I was able to install the plugin on a Craft 3.4 install earlier today with no issue.

**Comment by Geestig** [comment]
You can close this for now, I'll update next time I try to use it.

**Comment by mark-adigital** [comment]
Ok, thanks!
