### ISSUE TITLE
Prevent from showing for specific templates

### ISSUE THREAD

**Issue by skoften** [a-digital/cookie-consent-banner#2]
I would like to prevent the banner from popping up on certain templates. Can't find any way to accomplish this. 

Thanks!

**Comment by mark-adigital** [comment]
Hey,

To be honest, I'll have to look into the best way to implement this but at first glance I'm more inclined to add a new setting and then perform the check based on entry types rather than templates.

Will let you know when I have some time to look at it.

Mark

**Comment by skoften** [comment]
Hi Mark,

Maybe it's an idea to create a little tag that generates the popup, instead doing to behind the scenes? This way I can add it to my header and skip if for specific URL segments/pages.

Cheers

**Comment by mark-adigital** [comment]
Thanks for the suggestion, but to be honest I'm not sure I'd favour that approach as it introduces a breaking change for anyone else already using the plugin, and I think part of the utility of it is that it's just 'plug and play' with fairly minimal setup in the CP. Choosing entry types to exclude is effectively based on templates in most setups, keeps everything centralised in the plugin settings and means it's just a case of selecting the types where the banner shouldn't appear rather than going through and adding the code to each template where it should display, which most of the time is probably going to be the vast majority.

**Comment by aarmitage** [comment]
Hi,

We've considered this and feel that on balance, it's not something we're going to add to the plugin at this time. Cookies would persist across templates in most cases so excluding the message from some pages wouldn't seem to make sense for the majority of users.

Thanks for your feedback and suggestion though!

Cheers,
Andrew

**Comment by skoften** [comment]
Hi,

Cookies indeed perists across templates, but not if you're using a template in a mobile webview. This is now the issue for us; the modal is shown in our app on iOS/Android, and they will keep popping up because most webviews won't accept cookies (such as Facebook in-app webviews). This is where we would like to prevent the plugin generating the modal.

**Comment by skoften** [comment]
Awesome!

**Comment by mark-adigital** [comment]
Great!

**Comment by john-henry** [comment]
Hi @mark-adigital any suggestions how you might exclude this from say an RSS feed template or even error templates etc?

**Comment by mark-adigital** [comment]
Hi @john-henry - I've added a couple of checks before the banner is included for the content type and status code. Seems to be working as expected for me, so I've added a new pre-release version 1.1.3-beta.1, are you able to test that on your end? Thanks

**Comment by john-henry** [comment]
Hi @mark-adigital Ill give this a test but I don't know if it will suit what I want to do.

an RSS template I manually create or say an amp template I manually create. Or even the login page for Craft. I don't want the Cookie Consent banner appearing on those pages. None of them are Entry types or Categories. How would I exclude them from the a banner showing.

I suppose its an enhancement request really. Maybe like a Matrix type field in the plugins settings that you could add urls or regex to exclude them.

**Comment by john-henry** [comment]
@mark-adigital Seems to be ok this end thanks

**Comment by mark-adigital** [comment]
@john-henry  Great - I've fully released this update now

**Comment by PaulCWoods** [comment]
Hi. Yes it would be great to exclude templates as well. It's appearing in AMP pages on my site which breaks the validation.
