### ISSUE TITLE
No plugin exists with the handle "cookie-consent-banner"

### ISSUE THREAD

**Issue by martinsmith** [a-digital/cookie-consent-banner#23]
Hi, installation fails on Craft 3.4.17.1, it failed on CL and also via Control Panel.

UPDATE:  Just noticed the plugin IS actually installed after the error is shown?!?

**Comment by mark-adigital** [comment]
Hey - I just tried this via the CP and had no error. For some reason I didn't get any notification of the update you made, but that's weird. Is the plugin working as expected?

**Comment by mark-adigital** [comment]
Closing on account of no update.
