### ISSUE TITLE
Works fine locally, fails to instantiate CookieConsentBannerAsset upon deploy.

### ISSUE THREAD

**Issue by Geestig** [a-digital/cookie-consent-banner#24]
I get the following error upon deploying to another environment.

`Failed to instantiate component or class "adigital\cookieconsentbanner\assetbundles\cookieconsentbanner\CookieConsentBannerAsset"`

**Comment by mark-adigital** [comment]
Sorry for the long delay in replying - did this issue persist? It's an odd one given the plugin is installed on quite a lot of sites and isn't something that's been reported previously.

**Comment by Geestig** [comment]
I'll close this issue for now. Have opted to use a JS library instead. In case it would ever resurface I'll open a new ticket.
