### ISSUE TITLE
Undefined variable: entryTypeUid

### ISSUE THREAD

**Issue by bretthoran1** [a-digital/cookie-consent-banner#25]
Hi, Getting this error for _only some users_ which is causing an Internal Server Error.
**Undefined variable: entryTypeUid in .../vendor/adigital/cookie-consent-banner/src/CookieConsentBanner.php:166**

On Craft 3.4.30

**Comment by aarmitage** [comment]
Hi @bretthoran1 - thanks for getting in touch and using our plugin. Our developer who's best placed to answer your question here is on vacation this week - back on Monday. Hopefully you can bear with us until next week when we can look into this further for you.

**Comment by mark-adigital** [comment]
Hi @bretthoran1 , hopefully the new release will resolve this issue for you. Thanks.

**Comment by mark-adigital** [comment]
Closing due to hopeful fix in newest release and lack of further feedback.
