### ISSUE TITLE
Banner always on top.

### ISSUE THREAD

**Issue by jjacinto0** [a-digital/cookie-consent-banner#29]
Hi,

I installed and activated the plugin and its working but its always at the top of the page.

I change the position to bottom and the preview is correct but its always on top when I view it in actual page.

Thank you.

**Comment by mark-adigital** [comment]
Hi @jjacinto0 - I just ran a test and all appears to be working for me, do you have any more info please? Thanks.

**Comment by mark-adigital** [comment]
Just thought of a reason why this might have occurred - if you have the setting to preload the banner CSS enabled but haven't generated any critical CSS for your site, it would look as you describe. To address this, either generate your critical CSS or if you won't be using that, just toggle the preload option off.

**Comment by jjacinto0** [comment]
Hi @mark-adigital,

Thank you for your advice, The banner position was fixed after I disabled the Preload CSS.

This issue is now solved.

**Comment by mark-adigital** [comment]
Great! Thanks for letting me know.
