### ISSUE TITLE
How to show banner again?

### ISSUE THREAD

**Issue by felixfischer** [a-digital/cookie-consent-banner#33]
We need to be able to give users the choice to revoke their consent. How can we show the banner again after the user made their decision?

On the first page, where the user makes their decision, there remains a small tab at the bottom with which you can re-enable the popup. But when you navigate to another page the tab is no longer there, and there's also no global `cookieconsent` variable anymore.

**Comment by mark-adigital** [comment]
The banner will reappear when the cookie called `cookieconsent_status ` expires, so an easy way to force the banner to be redisplayed would be to clear it through JS for anyone who hasn't made a recent choice. You can also use the 'Expiry Days' field to set how long the preference should be stored for.

**Comment by felixfischer** [comment]
Thanks, @mark-adigital! Much appreciated!
