### ISSUE TITLE
FR: Translating messages..

### ISSUE THREAD

**Issue by wmdhosting** [a-digital/cookie-consent-banner#34]
Any chance to add For  Banner text  TAB multilang options..
![Snag_1e9fc66](https://user-images.githubusercontent.com/76176291/104333867-fe959700-54f1-11eb-84c5-398724deb597.png)

**Comment by aarmitage** [comment]
![104333867-fe959700-54f1-11eb-84c5-398724deb597](https://user-images.githubusercontent.com/1152884/118470795-ef706100-b6fe-11eb-963c-e4a8cbe413b1.png)

**Comment by mark-adigital** [comment]
Hey @wmdhosting , this is actually already possible with a static translations file as detailed in [this conversation](https://github.com/a-digital/cookie-consent-banner/issues/3#issuecomment-417697974)

Hope that helps!
