### ISSUE TITLE
Palette colours not being saved

### ISSUE THREAD

**Issue by jmdentand** [a-digital/cookie-consent-banner#35]
The colour options stopped working for me. It seems to be related to the hash sign for hexadecimal colours. 

The colour information is saved without the "#" character, which causes problem when the banner is displayed (the banner is transparent).

<img width="1060" alt="Screenshot 2021-05-17 at 14 44 24" src="https://user-images.githubusercontent.com/42352/118498914-62d59b00-b71e-11eb-90d9-95b28b87ac88.png">

Any idea on how to solve this (appart from overriding the styling)? Thanks!

**Comment by illiterati** [comment]
I am seeing the same issue, using Craft 3.6.15.

**Comment by gjhead** [comment]
I am also seeing this on Craft Pro 3.6.15.

**Comment by mark-adigital** [comment]
Thanks for the pointer @jmdentand , as you say it seems Craft has changed how these values are stored to drop the '#'. I've made updates today so that the character is re-added where appropriate if it's missing and have just created a new release.
