### ISSUE TITLE
Cookie Consent Banner not working

### ISSUE THREAD

**Issue by brianwachira** [a-digital/cookie-consent-banner#36]
Hi there,
I have followed the installation instructions on [the readme](https://github.com/a-digital/cookie-consent-banner#installation)
Unfortunately the banner is not displaying on the site. 
What could be the problem?
I am using `Craft CMS 3.4.16`

**Comment by mark-adigital** [comment]
Hi - sorry for the delay. Did you ever have any joy with this? The plugin is in use on a lot of websites so I don't believe there's any fundamental issues. Have you checked out the plugin settings to make sure the banner is being auto-injected on every page or on entries/categories appropriately?
