### ISSUE TITLE
Banner getting blocked

### ISSUE THREAD

**Issue by samuelbirch** [a-digital/cookie-consent-banner#4]
Hi Guys,

The cookie banner is getting blocked by the AdGuard chrome extension: https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg?hl=en

this is due to the injected styles that is does for the class names: .cc-banner & .cc-window.

I don't know if they are targeting your plugin directly or if its a coincidence? As css classname change would sort it.

Cheers

**Comment by mark-adigital** [comment]
Hi,

I just installed the extension but couldn't see the issue - can you share a URL please and are you certain there isn't something else at fault here?

Thanks,

Mark

**Comment by mark-adigital** [comment]
Hi,

Were you able to look into this and do you still feel the fault is with the plugin? We haven't ruled out updating the class names as you suggest, but given we couldn't replicate the issue here I was hoping you may have some additional detail first.

Thanks,

Mark

**Comment by mark-adigital** [comment]
Closing issue as no further feedback received.
