### ISSUE TITLE
Craft 4 Support

### ISSUE THREAD

**Issue by gjhead** [a-digital/cookie-consent-banner#41]
Any plans to update this for Craft 4?

**Comment by aarmitage** [comment]
Yes, we have and expect to complete this over the next few weeks. We're hoping to roll this out mid-late July subject to how other client projects fall.

**Comment by mark-adigital** [comment]
Hey @gjhead  - I was working on the Craft 4 port yesterday which appears to be working fine for me on our demo site. If you are able to include the Craft 4 version in a dev site ahead of release for further testing, that would be hugely appreciated. You can do that by including this reference in your `composer.json` file:

`"adigital/cookie-consent-banner": "dev-master",`

And then running composer update.

Just let me know if you hit any bugs or problems.
