### ISSUE TITLE
What happens if people click 'Decline' or 'Accept cookies'?

### ISSUE THREAD

**Issue by arentsen** [a-digital/cookie-consent-banner#46]
What happens if people click 'Decline' or 'Accept cookies'?

**Comment by MalcolmJohnston** [comment]
When you click 'Decline' or 'Accept Cookies' then a cookie is stored called `cookieconsent_status`.

When accepting the value stored is `allow`.
When declining the value stored is `deny`.

**Comment by aarmitage** [comment]
Thank you @MalcolmJohnston - we've obviously missed this issue. @arentsen I'll close it for now as hopefully this helps.
