### ISSUE TITLE
Cannot read properties of undefined (reading 'initialise')

### ISSUE THREAD

**Issue by vinodsnayvik** [a-digital/cookie-consent-banner#47]
Hi,
The Auto-inject is enabled in settings. I checked that in the website we have ```window.cookieconsent.initialise()``` . The CSS link is generating in website: 
```
<link href="https://example.com/web/cpresources/16b26a1a/css/cookieconsent.min.css?v=1668675871" rel="stylesheet">
```
but I did not get any cookieconsent.min.js.

The setting I'm using is default. Am i doing something wrong ?

**Comment by aarmitage** [comment]
The link for the js file should be found at the end of the page before the closing HTML tag. Did you manage to get the plugin to work for you?
