### ISSUE TITLE
Banner Not showing.

### ISSUE THREAD

**Issue by klick** [a-digital/cookie-consent-banner#5]
Hello. 
I have installed and configured the Banner. How do I make it show up on the front end? Am I missing something?

**Comment by mark-adigital** [comment]
Hi,

This seems odd and it's not something that has been reported previously. How have you configured the banner, and is it possible you've previously accepted the cookies? If so, you will need to clear your cookies before you see the banner again, which may explain this. Do you also have a URL I can visit?

Thanks,

Mark

**Comment by klick** [comment]
It’s working now although it feels a bit shaky. Might be overworked me. Thanks for the plugin!

**Comment by mark-adigital** [comment]
Ok, good to know - and no worries!
