### ISSUE TITLE
Version number issue

### ISSUE THREAD

**Issue by rogerdawkins** [a-digital/cookie-consent-banner#7]
I can't install V1.1.5 through Composer but it wasn't obvious initially why. But I think it's to do with the Github Tags. They go up to v1.1.3 but there is no v1.1.4 or v1.1.5. There is 1.1.4 and 1.1.5 (WITHOUT the leading v).

**Comment by mark-adigital** [comment]
Thanks - have edited the releases so should be resolved now.
